### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by OlafHaalstra** [CMEPW/BypassAV#7]
Hi,

Thanks for sharing the awesome resource. Quick question, how did you so beautifully render the mindmap to be 'landscape' and 'chronological'? If I look at https://cmepw.github.io/BypassAV it looks very different.

Best regards,

Olaf

**Comment by jenaye** [comment]
Hello @OlafHaalstra, sorry for the time of answer.
The mindmap was made with xmind software, however it makes contributions difficult.
After reflection with @noraj  we opted for a version in markdown with html rendering (at each merge on the main branch the site is updated, thank you @darkweak  for that) 

You have a lot of templates.
There are all shapes and colors (palettes are integrated to change the whole visual) 

![image](https://user-images.githubusercontent.com/15458329/218565237-e6f631b2-369f-4fa5-a04c-03cf155a5043.png)
